### ISSUE TITLE
HMR doesn't work in projects that use Plugins that use workers

### ISSUE THREAD

**Issue by shiv19** [NativeScript/worker-loader#41]
https://github.com/EddyVerbruggen/nativescript-particle/issues/7
[NativeScript6 Particle Plugin HMR issue.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/3384516/NativeScript6.Particle.Plugin.HMR.issue.zip)

HMR doesn't work when using nativescript-particle plugin.

This problem did not exist in older versions of dev-webpack

**Comment by AtoianAvetik** [comment]
@DimitarTachev 
What you can say about this small plugin https://github.com/TrigenSoftware/hmr-filter-webpack-plugin, can it help as a workaround?

**Comment by DimitarTachev** [comment]
Hi @AtoianAvetik,

Thanks for your help!

Unfortunately, this plugin won't change the problematic behavior as the Worker chunks are already excluded from the HMR updates (they are generated by another Webpack process). We need the opposite logic, the Worker chunks should be **included** in the hot updates in order to avoid the app restart. As I've already mentioned, this issue should be handled in the `nativescript-worker-plugin` itself, as it's spawning a child Webpack process with a custom config.

**Comment by AtoianAvetik** [comment]
@DimitarTachev, thanks for such a quick reply. Then we will wait for other news from you. Thanks!

**Comment by KristianDD** [comment]
**Acceptance criteri **
Initial setup:
1. Download repository
2. In `demo-angular` - `npm i --save-exact nativescript-worker-loader@next`

- [ ] Changes in application files should trigger just refresh
- [ ] Changes in worker should trigger a restart of the application
- [ ] Changes in shared modules, like [this one](https://github.com/NativeScript/worker-loader/blob/master/demo-angular/app/shared.ts), should trigger a restart.
